export const stepsData = [
  {
    id: 0,
    type: "single-choice",
    title: "What school are you in?",
    subtitle: "Select any one.",
    highlight: "school",
    options: [
      "Amity International School",
      "International School of Estonia",
      "German European School, Singapore",
      "International School of Zurich",
    ],
    buttonText: "Next",
  },
  {
    id: 1,
    type: "drop-down",
    title: "What grade are you in?",
    subtitle: "Select any one.",
    highlight: "grade",
    options: [
      "8th Grade",
      "9th Grade",
      "10th Grade",
      "11th Grade",
      "12th Grade",
    ],
    buttonText: "Next",
  },
  {
    id: 2,
    type: "single-choice",
    title: "What are you here to figure out?",
    subtitle: "Select what applies.",
    highlight: "I want to:",
    options: [
      "🔎 Explore Careers",
      "🌎 Create An Impact",
      "🛠️ Solve Problems",
      "🧠 Understand Myself Better",
    ],
    buttonText: "Next",
  },
  {
    id: 3,
    type: "multi-choice",
    title: "Pick the subjects that excite you",
    subtitle: "You don’t have to be great at it. Select up to five",
    highlight: "I enjoy:",
    options: [
      {
        icon: "🎭",
        title: "Drama",
        description: "Act, perform, take the stage",
      },
      {
        icon: "🎵",
        title: "Music",
        description: "Play, sing, make beats",
      },
      {
        icon: "🎨",
        title: "Art & Drawing",
        description: "Draw, paint, design",
      },
      {
        icon: "💻",
        title: "Computers & Tech",
        description: "Coding, games, building apps",
      },
      {
        icon: "⚒️",
        title: "Building & Making",
        description: "Invent, build, create cool stuff",
      },
    ],
    buttonText: "Next",
  },
  {
    id: 4,
    type: "multi-choice",
    title: "What are your top super skills?",
    subtitle: "Select your best skills.",
    highlight: "I am good at:",
    options: [
      {
        icon: "🎭",
        title: "Drama",
        description: "Act, perform, take the stage",
      },
      {
        icon: "🎵",
        title: "Music",
        description: "Play, sing, make beats",
      },
      {
        icon: "🎨",
        title: "Art & Drawing",
        description: "Draw, paint, design",
      },
      {
        icon: "💻",
        title: "Computers & Tech",
        description: "Coding, games, building apps",
      },
      {
        icon: "⚒️",
        title: "Building & Making",
        description: "Invent, build, create cool stuff",
      },
    ],
    buttonText: "Next",
  },
  {
    id: 5,
    type: "multi-choice",
    title: "What issues do you care about?",
    subtitle: "Select any three",
    highlight: "I care about:",
    options: [
      "../assets/sdg/image-1.svg",
      "../assets/sdg/image-5.svg",
      "../assets/sdg/image-3.svg",
      "../assets/sdg/image-4.svg",
      "../assets/sdg/image-5.svg",
      "../assets/sdg/image-6.svg",
      "../assets/sdg/image-1.svg",
      "../assets/sdg/image-5.svg",
      "../assets/sdg/image-3.svg",
      "../assets/sdg/image-4.svg",
      "../assets/sdg/image-5.svg",
      "../assets/sdg/image-6.svg",
    ],
    buttonText: "Show Me Careers",
  },
  {
    id: 6,
    type: "text",
    title: "What are your ambitions?",
    subtitle:
      "Tell us anything else you think we should know to guide better guide career development.",
    highlight: "Tap here to start typing...",
    buttonText: "Next",
  },
  {
    id: 7,
    type: "result",
    title: "Awesome!",
    subtitle:
      "Thanks for sharing that with us. Based on the subjects, skills, and issues you care about, we found some career matches for you. The more you share, the better recommendations you get.",
    showLoader: true,
  },
];
