export const stepsData = [
  {
    id: 0,
    type: "single-choice",
    title: "What school are you in?",
    subtitle: "Select any one.",
    highlight: "school",
    options: [
      "Amity International School",
      "International School of Estonia",
      "German European School, Singapore",
      "International School of Zurich",
    ],
    buttonText: "Next",
  },
  {
    id: 1,
    type: "drop-down",
    title: "What grade are you in?",
    subtitle: "Select any one.",
    highlight: "grade",
    options: [
      "8th Grade",
      "9th Grade",
      "10th Grade",
      "11th Grade",
      "12th Grade",
    ],
    buttonText: "Next",
  },
  {
    id: 2,
    type: "single-choice",
    title: "What are you here to figure out?",
    subtitle: "Select what applies.",
    highlight: "I want to:",
    options: [
      "Explore Careers",
      "Excel in Subjects",
      "Solve Problems",
      "Understand Myself Better",
    ],
    buttonText: "Next",
  },
  {
    id: 3,
    type: "multi-choice",
    title: "Pick the subjects that excite you",
    subtitle: "You can select up to 3.",
    highlight: "I enjoy:",
    options: [
      "AI / Drones",
      "Art & Drawing",
      "Computers & Tech",
      "Building & Making",
      "Math",
      "Science",
      "History",
      "Literature",
    ],
    buttonText: "Next",
  },
  {
    id: 4,
    type: "multi-choice",
    title: "What are your top super skills?",
    subtitle: "Select your best skills.",
    highlight: "I am good at:",
    options: [
      "Problem-Solving",
      "Creative Thinking",
      "Teamwork",
      "Presenting & Speaking",
      "Leadership",
      "Planning & Organizing",
    ],
    buttonText: "Next",
  },
  {
    id: 5,
    type: "multi-choice",
    title: "What issues do you care about?",
    subtitle: "Select all you share.",
    highlight: "I care about:",
    options: [
      "Health",
      "Education",
      "Poverty",
      "Environment",
      "Technology",
      "Equality",
      "Innovation",
      "Peace & Justice",
    ],
    buttonText: "Show Me Careers",
  },
  {
    id: 6,
    type: "text", // free input
    title: "What are your ambitions?",
    subtitle: "Tell us about your goals and dreams.",
    highlight: "Tap here to start typing...",
    buttonText: "Next",
  },
  {
    id: 7,
    type: "result",
    title: "Awesome!",
    subtitle:
      "Thanks for sharing that with us. Based on the subjects, skills, and issues you care about, we found some career matches for you. The more you share, the better recommendations you get.",
    showLoader: true,
  },
];
